import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Verified Affiliations
        </h1>

        <div className={styles.grid}>
          <a href="/issue" className={styles.card}>
            <h2>Issue Credential &rarr;</h2>
            <p>You will be asked to login with IDP from Authenticator App</p>
          </a>

          <a href="/verify" className={styles.card}>
            <h2>Verify Credential &rarr;</h2>
            <p>You will be asked to login with IDP from Authenticator App</p>
          </a>

        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
